sudo: required

# Choose a lightweight base image; we provide our own build tools.
language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

addons:
  - apt:
    packages:
    - shellcheck

matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.6.3 ALEXVER=3.1.3 HAPPYVER=1.19.3 BNFCURL=https://launchpad.net/ubuntu/+source/bnfc/2.4.2.0-2/+build/3378744/+files/bnfc_2.4.2.0-2_amd64.deb
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,alex-3.1.3,happy-1.19.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2 ALEXVER=3.1.7 HAPPYVER=1.19.5 BNFCURL=https://launchpad.net/ubuntu/+source/bnfc/2.8-4/+build/8400113/+files/bnfc_2.8-4_amd64.deb
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
 - echo $PATH
 - wget $BNFCURL -O bnfc.deb

install:
 - cabal update
 - cabal install mtl==2.2.1
 - sudo dpkg -i bnfc.deb

after_install:
 - cabal --version
 - ghc --version
 - bnfc --version
 - happy --version
 - alex --version

script:
 - make
 - make shellcheck
 - make test
